unbind r
bind r source-file ~/.tmux.conf
bind 'P' display-popup -E "tmux -L popup new-session -A -s popup"

# Split panes in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Status bar
set -g status-position top
set -g status-left-length 100
set -g status-style "bg=default"
set -g status-right "#{pane_current_command} #H %d-%m-%Y %H:%M"

# Pane Style
set -g pane-border-lines "heavy"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
